import type { Metadata } from "next";
import React from "react";
import { Inter, Ceviche_One, Comic_Neue } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import "../styles/globals.css";
import BootstrapClient from "../scripts/BootstrapClient";

import Navbar from "../components/NavBar"
import Footer from "../components/footer"

//declaring const variables
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <BootstrapClient/>
        <Footer/>
        {children}
      </body>
    </html>
  );
}